In [1]:
#### 41. How to sum a small array faster than np.sum? (★★☆)
#### 42. Consider two random array A and B, check if they are equal (★★☆)
#### 43. Make an array immutable (read-only) (★★☆)
#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)
#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)
#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)
#### 49. How to print all the values of an array? (★★☆)
#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [3]:
import numpy as np

In [6]:
#41
A = np.random.randint(0, 100, 10)
print(A)
np.add.reduce(A)

[38 15 38 62 16 43 25 15 72 87]


411

In [18]:
#42
A = np.random.randint(0, 10, 10)
B = np.random.randint(0, 10, 10)
print(np.equal(A, B))
print(np.allclose(A, B))
print(np.array_equal(A, B))

[False False False False  True False False False False False]
False
False


In [25]:
#43
A = np.random.random(10)
A[0] = 1.11
A.flags.writeable = False
try:
    A[0] = 1.22
except Exception:
    print("Cannot write to array")

Cannot write to array


In [57]:
#44
cartesian = np.random.randint(1, 10, (10, 2))
cartesian = cartesian.astype(np.float32)
print(cartesian)
#using apply along axis
get_radius = lambda x: np.sqrt(np.sum(np.square(x)))
get_theta = lambda x: np.arctan2(x[1], x[0])
get_polar = lambda x:  np.array([get_radius(x), get_theta(x)])
print(np.apply_along_axis(get_polar, -1, cartesian))


#using indexing
X, Y = cartesian[:, 0], cartesian[:, 1]
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[[4. 7.]
 [3. 5.]
 [4. 5.]
 [3. 2.]
 [4. 5.]
 [2. 5.]
 [2. 7.]
 [7. 4.]
 [4. 4.]
 [8. 6.]]
[[ 8.062258   1.0516502]
 [ 5.8309517  1.0303768]
 [ 6.4031243  0.8960554]
 [ 3.6055512  0.5880026]
 [ 6.4031243  0.8960554]
 [ 5.3851647  1.19029  ]
 [ 7.28011    1.2924967]
 [ 8.062258   0.5191461]
 [ 5.656854   0.7853982]
 [10.         0.6435011]]
[ 8.062258   5.8309517  6.4031243  3.6055512  6.4031243  5.3851647
  7.28011    8.062258   5.656854  10.       ]
[1.0516502 1.0303768 0.8960554 0.5880026 0.8960554 1.19029   1.2924967
 0.5191461 0.7853982 0.6435011]


In [62]:
#45
Z = np.random.random(10)
print(Z)
Z[Z.argmax()] = 0
print(Z)

[0.24256489 0.38892174 0.8679318  0.7679447  0.5055392  0.16779205
 0.79017351 0.42580716 0.95798378 0.66017352]
[0.24256489 0.38892174 0.8679318  0.7679447  0.5055392  0.16779205
 0.79017351 0.42580716 0.         0.66017352]


In [85]:
#46
#using np.meshgrid
Z = np.zeros((5,5), [('x', np.float32), ('y', np.float32)])
print(Z)
Z['x'], Z['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(1, 0, 5))
print(Z)

[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]]
[[(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]]


In [94]:
#47
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(C)
print(np.linalg.det(C))


[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]
3638.163637117973


In [91]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [95]:
#49
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [108]:
#50
A = np.random.randint(1, 100, (4,))
print(A)
Z = np.random.uniform(0, 100, (4,))
print(Z)
index = (np.abs(A-Z)).argmin()
print(index)
print(Z[index])

[29  3 79 70]
[15.16395001 69.74501213 24.81896708 58.7008438 ]
3
58.70084380176272
