In [2]:
#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [3]:
#61

import numpy as np

val = 44.5
Z = np.random.uniform(0, 100, (5, 3))
print(Z)
Z_ = np.abs(Z-val)
idx = np.argmin(Z_)
Z.flatten()[idx]

[[41.12628257 83.61502223  8.25611172]
 [99.60430285 67.56159919 34.04246691]
 [ 5.23693759 63.72735316 12.36129578]
 [19.44393245 57.26820661 26.24489971]
 [76.37748701 87.11913813 56.47965692]]


41.126282568875496

In [28]:
#62

A = np.random.random((1, 4))
B = np.random.random((3, 1))

it = np.nditer([A,B,None])
for x,y,z in it: 
    z[...] = x + y

print(it.operands[2])

[[1.62124187 1.01478437 1.64790625 1.43733291]
 [1.39678171 0.79032422 1.42344609 1.21287276]
 [1.52560862 0.91915112 1.552273   1.34169967]]


In [92]:
#63

class NamedArray(np.ndarray):

    def __new__(cls, name, *args):
        arr_obj = np.ndarray.__new__(cls, *args)
        arr_obj.name = name
        return arr_obj
    
    def __array_finalize__(self, obj):
        print('array finalize is called')
        if obj is None: return
        self.name = getattr(obj, 'name', "default_name")


named_arr = NamedArray("varray", (2, 2))
print(named_arr.name, named_arr)

example_array = np.zeros((3, 2)).view(NamedArray)
print(example_array.name)

array finalize is called
varray [[0.7092818  0.77295976]
 [0.24077747 0.17226737]]
array finalize is called
default_name


In [112]:
#64
I = np.random.randint(1, 10, 20)
Z = np.random.randint(1, 50, 10)
print(Z)
Z += np.bincount(I, minlength=len(Z))
print(Z)


#another solution
np.add.at(Z, I, 1)
print(Z)

[17 44 41 15  1 28 40 10 41 14]
[17 49 42 17  2 30 42 12 44 16]
[17 54 43 19  3 32 44 14 47 18]


In [119]:
#65
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
print(X)
print(I)
# X[I]
F = np.bincount(I,X)
F

[1, 2, 3, 4, 5, 6]
[1, 3, 9, 3, 4, 1]


array([0., 7., 0., 6., 5., 0., 0., 0., 0., 3.])

In [130]:
#66
w, h = 120, 80
image_arr = np.random.randint(0, 255, (w, h, 3))
uniq_colors = np.unique(image_arr.reshape(-1, 3), axis=0)
uniq_colors.shape

(9598, 3)

In [14]:
#67
A = np.random.randint(0, 10, (3, 24, 24, 255)).astype(np.uint8)
#both ways are fine
A1 = np.sum(A, axis=(-1, -2))
A2 = np.sum(A, axis=(-2, -1))
print(A1[2, :5])
print(A2[2, :5])

[27181 27088 27745 27643 27808]
[27181 27088 27745 27643 27808]


In [21]:
#68
D = np.random.uniform(0, 100, (100))
S = np.random.randint(0, 10, size=(100))
S_sum = np.bincount(S)
D_sum = np.bincount(S, weights=D)
print(D_sum/S_sum)

[40.06655951 49.9745553  38.16056542 46.49352204 29.77626875 47.55039022
 46.90995979 59.21371492 63.30200064 40.20505402]


In [31]:
#69

A = np.random.randint(0, 5, (4, 4))
B = np.random.randint(0, 5, (4, 4))

#soln1
print(np.diag(np.dot(A, B)))

#soln
print(np.sum(A*B, axis=1))

[ 6 18  4 17]
[ 6 16  8 11]


In [36]:
#70

A = np.arange(1, 6)
n = 3
B = np.zeros(A.size + (A.size-1) *n)
B[::n+1] = A
print(B)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]
