#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
#### 22. Normalize a 5x5 random matrix (★☆☆)
#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```
#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```
#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```
#### 29. How to round away from zero a float array ? (★☆☆)
#### 30. How to find common values between two arrays? (★☆☆)

In [1]:
import numpy as np
import numpy.random as randnp

In [7]:
#21
example_array = np.array([[0, 1], [1, 0]])
np.tile(example_array, (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [11]:
#22
def normalize(in_array):
    mu = np.mean(in_array, keepdims=True)
    sigma = np.std(in_array, keepdims=True)
    Z = (in_array - mu)/sigma
    return Z

input_array = np.random.random((5, 5))
normalize(input_array)

array([[-1.23414582,  1.36456939,  1.27958072,  1.30996725, -0.02524991],
       [ 0.94878031,  0.07183409, -1.08172699, -1.36576827, -0.41224388],
       [ 1.0893958 ,  1.19703098,  1.48496931, -1.58907395,  1.18071816],
       [ 0.57531431, -1.01650395, -0.43838038,  0.19171253,  0.14546473],
       [-0.91014345, -1.25361872, -0.26940821, -0.09876434, -1.14430972]])

In [13]:
#23
color_type = np.dtype([("r", np.ubyte), ("g", np.ubyte), ("b", np.ubyte), ("a", np.ubyte)])

In [15]:
#24
a = np.ones((5, 3))
b = np.ones((3, 2))
np.matmul(a, b)

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [29]:
#25
one_dim_array = np.random.randint(-10, 15, (10))
print(one_dim_array)
one_dim_array[(3<one_dim_array) & (8>one_dim_array)] *= -1
print(one_dim_array)

[11  4 -5 -5  4 -1 11 -3 13 11]
[11 -4 -5 -5 -4 -1 11 -3 13 11]


In [6]:
#26
print(sum(range(5),-1))
# from numpy import *
# print(sum(range(5),-1))
print(np.sum(range(5),-1))

9
10


In [29]:
#27
Z = np.random.randint(0, 10, (1))
print(Z)
# Z**Z # negative integer to negative integer power gives non-integer
2 << Z >> 2 #left-shift 2 by Z and then right-shift by 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

[0]


array([False])

In [35]:
#28

print(np.array(0) / np.array(0))       #nan
print(np.array(0) // np.array(0))     #0
print(np.array([np.nan]).astype(int).astype(float))    #some random number


nan
0
[-9.22337204e+18]


/var/folders/zw/8cs3hp9s53q_p69tftz7xhwr0000gq/T/ipykernel_12882/2273596654.py:3: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))       #nan
/var/folders/zw/8cs3hp9s53q_p69tftz7xhwr0000gq/T/ipykernel_12882/2273596654.py:4: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))     #0


In [44]:
#29
example_array = np.random.uniform(-100, 100, 10)
print(example_array)
np.where(example_array>0, np.ceil(example_array), np.floor(example_array))

[ -1.47896025 -24.96261024 -10.6599523   -9.76176066 -31.48853047
  35.01984979  31.03725116  64.98069683 -76.63266409  72.44159678]


array([ -2., -25., -11., -10., -32.,  36.,  32.,  65., -77.,  73.])

In [58]:
#30
a = np.random.randint(0, 20, 10)
b = np.random.randint(0, 20, 10)
print(a)
print(b)
np.intersect1d(a, b)

[ 9  1  5 13  4  2  5 11 13 17]
[ 9 13  8 12 16 16  2  0 12  1]


array([ 1,  2,  9, 13])