#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)
#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```
#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)
#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)
#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)
#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)
#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
#### 40. Create a random vector of size 10 and sort it (★★☆)

In [1]:
import numpy as np

In [4]:
#31
np.seterr(all='warn')
Z = np.ones(1)/0

/var/folders/zw/8cs3hp9s53q_p69tftz7xhwr0000gq/T/ipykernel_7248/116594305.py:3: RuntimeWarning: divide by zero encountered in divide
  Z = np.ones(1)/0


In [19]:
#32
np.sqrt(-1) == np.emath.sqrt(-1)

False

In [11]:
#33
print(np.datetime64('today') - np.timedelta64(1, 'D'))
print(np.datetime64('today'))
print(np.datetime64('today') + np.timedelta64(1, 'D'))


2022-12-26
2022-12-27
2022-12-28


In [16]:
#34
np.arange('2016-06', '2016-07', dtype='datetime64[D]')

array(['2016-06-01', '2016-06-02', '2016-06-03', '2016-06-04',
       '2016-06-05', '2016-06-06', '2016-06-07', '2016-06-08',
       '2016-06-09', '2016-06-10', '2016-06-11', '2016-06-12',
       '2016-06-13', '2016-06-14', '2016-06-15', '2016-06-16',
       '2016-06-17', '2016-06-18', '2016-06-19', '2016-06-20',
       '2016-06-21', '2016-06-22', '2016-06-23', '2016-06-24',
       '2016-06-25', '2016-06-26', '2016-06-27', '2016-06-28',
       '2016-06-29', '2016-06-30'], dtype='datetime64[D]')

In [20]:
#35
#((A+B)(-A/2)) in place
A = np.random.random((4, 4))
B = np.random.random((4, 4))
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=B)

array([[-0.82002956, -0.2886995 , -0.04867885, -0.66747504],
       [-0.41732551, -0.00825149, -0.30425351, -0.06261942],
       [-0.30919088, -0.11391003, -0.01691676, -0.72903375],
       [-0.02315537, -0.02373846, -0.21642549, -0.01091247]])

In [29]:
#36
A=np.random.uniform(0, 10, 10)
print(A)
print(A-A%1)
print(A//1)
print(np.floor(A))
print(A.astype(int))

[2.39454315 5.43923747 2.9152241  5.71864455 7.73324681 4.94680381
 2.98208012 0.46296886 7.17794264 9.96545106]
[2. 5. 2. 5. 7. 4. 2. 0. 7. 9.]
[2. 5. 2. 5. 7. 4. 2. 0. 7. 9.]
[2. 5. 2. 5. 7. 4. 2. 0. 7. 9.]
[2 5 2 5 7 4 2 0 7 9]


In [48]:
#37
#with broadcasting 1d array to 2d array
A = np.zeros((5, 5))
A += np.arange(0, 5)
print(A)

#using np.tile
B = np.tile(np.arange(0, 5, dtype=np.float32), (5, 1))
print(B)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [50]:
#38
# using np.fromiter()
def integer_generator():
    import random
    for i in range(10):
        yield random.randint(0, 100)

np.fromiter(integer_generator(), dtype=np.float32)

array([81., 94., 65., 69.,  5., 12., 88., 77., 39., 67.], dtype=float32)

In [53]:
#39
A = np.linspace(0, 1, 11, endpoint=False)[1:]
A

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [56]:
#40
#using np.sort
A = np.sort(np.random.random(10))
A

array([0.04083589, 0.23566137, 0.23584033, 0.37298286, 0.53548661,
       0.62977296, 0.7223107 , 0.81933858, 0.82873003, 0.94236404])