#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)
#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)
#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?
#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [29]:
import numpy as np

In [5]:
#51

Z = np.zeros((5, 5), dtype=[('x', np.int64), ('y', np.int64)])
print(Z)
position = np.dtype([('x', np.int64), ('y', np.int64)])
color = np.dtype([('r', np.int64), ('g', np.int64), ('b', np.int64)])
Z1 = np.zeros((3, 3), dtype=[('position', position), ('color', color)])
Z1

[[(0, 0) (0, 0) (0, 0) (0, 0) (0, 0)]
 [(0, 0) (0, 0) (0, 0) (0, 0) (0, 0)]
 [(0, 0) (0, 0) (0, 0) (0, 0) (0, 0)]
 [(0, 0) (0, 0) (0, 0) (0, 0) (0, 0)]
 [(0, 0) (0, 0) (0, 0) (0, 0) (0, 0)]]


array([[((0, 0), (0, 0, 0)), ((0, 0), (0, 0, 0)), ((0, 0), (0, 0, 0))],
       [((0, 0), (0, 0, 0)), ((0, 0), (0, 0, 0)), ((0, 0), (0, 0, 0))],
       [((0, 0), (0, 0, 0)), ((0, 0), (0, 0, 0)), ((0, 0), (0, 0, 0))]],
      dtype=[('position', [('x', '<i8'), ('y', '<i8')]), ('color', [('r', '<i8'), ('g', '<i8'), ('b', '<i8')])])

In [26]:
#52
with np.printoptions(precision=2):
    Z = np.random.uniform(0, 10, (10, 2))
    X, Y = np.atleast_2d(Z[:, 0], Z[:, 1])

    D = np.sqrt((X-X.T)**2 + (Y-Y.T)**2)
    print(D)

[[ 0.    3.75  1.06  2.87  8.07  4.71  5.94  6.88  8.84 10.99]
 [ 3.75  0.    3.9   3.23  4.87  2.74  3.72  3.14  6.47  7.3 ]
 [ 1.06  3.9   0.    2.07  8.55  4.19  5.37  7.    8.19 10.89]
 [ 2.87  3.23  2.07  0.    8.09  2.28  3.38  5.91  6.14  9.33]
 [ 8.07  4.87  8.55  8.09  0.    6.95  7.31  3.03  9.    5.92]
 [ 4.71  2.74  4.19  2.28  6.95  0.    1.24  4.25  4.17  7.14]
 [ 5.94  3.72  5.37  3.38  7.31  1.24  0.    4.37  2.93  6.46]
 [ 6.88  3.14  7.    5.91  3.03  4.25  4.37  0.    5.99  4.39]
 [ 8.84  6.47  8.19  6.14  9.    4.17  2.93  5.99  0.    5.9 ]
 [10.99  7.3  10.89  9.33  5.92  7.14  6.46  4.39  5.9   0.  ]]


In [79]:
#53
#https://stackoverflow.com/a/4396247/5989906

Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
print(Z, Z.dtype)
print(Y, Y.dtype)
print(id(Z))
print(id(Y))
Y[:] = Z
print(Z, Z.dtype)
print(Y, Y.dtype)
print(id(Z))
print(id(Y))

#simpler way
print('\n')
Z = (np.random.rand(10)*100).astype(np.float32)
print(Z)
print(Z.astype(np.int32, copy=False))

[76.22652  42.773296 68.49126  66.03875  14.367308 37.343964 73.59709
 25.085056 64.39582  42.76346 ] float32
[1117287418 1110120411 1116273542 1115952087 1097195646 1108697144
 1116942774 1103670834 1115736745 1110117832] int32
140470612657904
140470612658768
[1.06e-43 5.89e-44 9.53e-44 9.25e-44 1.96e-44 5.18e-44 1.02e-43 3.50e-44
 8.97e-44 5.89e-44] float32
[76 42 68 66 14 37 73 25 64 42] int32
140470612657904
140470612658768


[44.763268  92.98875   20.246092  17.617697  12.04367   75.64875
  4.2615685 71.67784   98.685936  74.89435  ]
[44 92 20 17 12 75  4 71 98 74]


In [91]:
#54
from io import StringIO
s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=',', dtype=np.float16)
print(Z)

# read from file
# with open("input.txt", "r") as infile:
#     print(infile.read())

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


In [114]:
#55

Z = np.random.rand(1, 2, 3)*100
Y = np.ndenumerate(Z)
for idx, value in Y:
    print(idx, value, Z[idx])
print()
X = np.ndindex(Z.shape)
for idx in X:
    print(idx, Z[idx])

(0, 0, 0) 69.85589962095072 69.85589962095072
(0, 0, 1) 56.24029821295126 56.24029821295126
(0, 0, 2) 77.77552504152008 77.77552504152008
(0, 1, 0) 4.303708665379835 4.303708665379835
(0, 1, 1) 96.85095396466504 96.85095396466504
(0, 1, 2) 75.17107807241034 75.17107807241034

(0, 0, 0) 69.85589962095072
(0, 0, 1) 56.24029821295126
(0, 0, 2) 77.77552504152008
(0, 1, 0) 4.303708665379835
(0, 1, 1) 96.85095396466504
(0, 1, 2) 75.17107807241034


In [138]:
#56
GD = np.random.normal(size=(2, 5))
GD

X, Y = np.meshgrid(np.linspace(0, 1, 5, endpoint=False), np.linspace(0, 1, 5, endpoint=False))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[1.         0.98019867 0.92311635 0.83527021 0.72614904]
 [0.98019867 0.96078944 0.90483742 0.81873075 0.71177032]
 [0.92311635 0.90483742 0.85214379 0.77105159 0.67032005]
 [0.83527021 0.81873075 0.77105159 0.69767633 0.60653066]
 [0.72614904 0.71177032 0.67032005 0.60653066 0.52729242]]


In [151]:
#57
m , n = 5, 5
Z = np.zeros((m, n))
np.put(Z, np.random.choice(range(m*n), 3, replace=False), np.random.choice(range(m*n), 3, replace=False))
Z

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., 22.],
       [16.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0., 20.,  0.,  0.,  0.]])

In [168]:
#58

Z = np.random.random((5, 5))
# M = np.mean(Z, axis=1, keepdims=True)
# or
M = np.mean(Z, axis=1).reshape(-1, 1)
D = Z - M
print(Z)
print(M)
print(D)

[[0.70775376 0.40977007 0.73945243 0.65338459 0.42602411]
 [0.81299631 0.75502124 0.58931499 0.03297898 0.30736788]
 [0.02220381 0.89350398 0.17221759 0.52682242 0.22578446]
 [0.4450455  0.63309661 0.43588678 0.04790393 0.63703955]
 [0.03802966 0.08914473 0.59877583 0.13571801 0.68258014]]
[[0.58727699]
 [0.49953588]
 [0.36810645]
 [0.43979447]
 [0.30884967]]
[[ 0.12047677 -0.17750693  0.15217543  0.0661076  -0.16125288]
 [ 0.31346043  0.25548536  0.08977911 -0.4665569  -0.192168  ]
 [-0.34590264  0.52539752 -0.19588886  0.15871597 -0.14232199]
 [ 0.00525102  0.19330213 -0.0039077  -0.39189054  0.19724508]
 [-0.27082002 -0.21970494  0.28992616 -0.17313166  0.37373046]]


In [176]:
#59

Z = np.random.random((5, 5))
print(Z)
print(Z[:,1].argsort())
Z = Z[Z[:,1].argsort()]
Z

[[0.77365558 0.38104836 0.20464397 0.20098149 0.59788789]
 [0.51791459 0.02094874 0.96157599 0.66633075 0.816343  ]
 [0.56674237 0.16116713 0.5303284  0.99356149 0.50519323]
 [0.08405426 0.29252945 0.66353199 0.12896937 0.16748597]
 [0.79503811 0.23507729 0.3817072  0.97735518 0.00608495]]
[1 2 4 3 0]


array([[0.51791459, 0.02094874, 0.96157599, 0.66633075, 0.816343  ],
       [0.56674237, 0.16116713, 0.5303284 , 0.99356149, 0.50519323],
       [0.79503811, 0.23507729, 0.3817072 , 0.97735518, 0.00608495],
       [0.08405426, 0.29252945, 0.66353199, 0.12896937, 0.16748597],
       [0.77365558, 0.38104836, 0.20464397, 0.20098149, 0.59788789]])

In [181]:
#60

Z = np.random.random((5, 5))
Z[0, :] = np.nan
np.isnan(Z).all(axis=1)

array([ True, False, False, False, False])