In [1]:
#### 11. Create a 3x3 identity matrix (★☆☆)

#### 12. Create a 3x3x3 array with random values (★☆☆)

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

#### 17. What is the result of the following expression? (★☆☆)

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [2]:
import numpy as np

In [8]:
#11
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
#12
np.random.random((3, 3, 3))

array([[[0.92014164, 0.18202646, 0.32611167],
        [0.54008539, 0.83962966, 0.75389468],
        [0.16399476, 0.37107192, 0.65859281]],

       [[0.55613276, 0.04640395, 0.16394694],
        [0.96653481, 0.85994897, 0.78859356],
        [0.71070178, 0.23731437, 0.48436853]],

       [[0.25412259, 0.59360705, 0.52224394],
        [0.27273096, 0.29059621, 0.35182656],
        [0.1520192 , 0.77690638, 0.67887102]]])

In [17]:
#13
example_array = np.random.random((10, 10))
print(np.max(example_array), example_array.min())

0.9984457082974492 0.008121211856469523


In [28]:
#14
example_array = np.random.random((30))
example_array.mean() 

0.5217217513768803

In [40]:
#15
example_array = np.ones((5, 5))
assert len(example_array.shape) == 2
example_array[1:-1, 1:-1] = 0
example_array

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [3]:
#16
example_array = example_array = np.ones((5, 5))

#using np.concatenate
first_dim_border = np.zeros((1, example_array.shape[1]))
intermediate_array = np.concatenate((first_dim_border, example_array, first_dim_border))
second_dim_border = np.zeros((intermediate_array.shape[0], 1))
final_array = np.concatenate((second_dim_border, intermediate_array, second_dim_border), axis=1)
# print(final_array)

#using np.pad
padded_array = np.pad(example_array, (1, 1), mode="constant", constant_values=0)
print(padded_array)

#using indexing for existing array
example_array[:, [0, -1]] = 0
example_array[[0, -1], :] = 0
print(example_array)


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [77]:
#17
0 * np.nan          #np.nan
np.nan == np.nan    #False
np.inf > np.nan     #False
np.nan - np.nan     #np.nan
np.nan in set([np.nan]) #True
0.3 == 3 * 0.1      #False

False

In [5]:
#18

example_array = np.arange(1, 5)
np.diag(example_array, k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [21]:
#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[::2, 1::2] = 1
checkerboard[1::2, ::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [22]:
#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
np.unravel_index(99, (6, 7, 8))

(1, 5, 3)