In [1]:
#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [56]:
import numpy as np

In [8]:
#71

A = np.random.rand(5, 5, 3)
B = np.random.rand(5, 5)

product = A * B[:,:, None]
print(product)

[[[0.01221519 0.00210556 0.01465449]
  [0.107672   0.04466066 0.39043199]
  [0.23084361 0.30355058 0.10849954]
  [0.12635157 0.1054929  0.1119361 ]
  [0.10743211 0.26488618 0.21992891]]

 [[0.45780421 0.57105547 0.20289465]
  [0.02953706 0.44066629 0.48670194]
  [0.4167123  0.35864032 0.02067979]
  [0.03549533 0.05842049 0.04718965]
  [0.84952924 0.48351051 0.62446983]]

 [[0.03077867 0.03573011 0.02987542]
  [0.01981632 0.0114922  0.03594303]
  [0.50810886 0.5730902  0.59833285]
  [0.00230062 0.00387493 0.00527454]
  [0.0597263  0.34982951 0.58311418]]

 [[0.13766959 0.218378   0.11092094]
  [0.750296   0.69879035 0.86729446]
  [0.08651573 0.15439243 0.0983143 ]
  [0.09599017 0.02131906 0.04245634]
  [0.77605135 0.8006781  0.5903107 ]]

 [[0.08189123 0.09220897 0.05708414]
  [0.18689563 0.15630759 0.65508379]
  [0.19221842 0.08295271 0.33691478]
  [0.60071057 0.48081355 0.16068431]
  [0.43442584 0.51140629 0.39484613]]]


In [13]:
#72

A = np.random.rand(2, 4)
print('A before')
print(A)
print()
A[[0, 1]] = A[[1, 0]]
print('A after')
print(A)

A before
[[0.26678252 0.83401601 0.76646706 0.5358768 ]
 [0.68743908 0.15792412 0.67412461 0.15146115]]

A after
[[0.68743908 0.15792412 0.67412461 0.15146115]
 [0.26678252 0.83401601 0.76646706 0.5358768 ]]


In [15]:
#73 WTH
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)
print(G.shape)

[( 2, 18) ( 2, 31) (13, 18) (13, 42) (14, 51) (14, 76) (18, 31) (18, 42)
 (25, 67) (25, 76) (29, 34) (29, 99) (34, 99) (41, 67) (41, 91) (43, 46)
 (43, 80) (46, 80) (51, 76) (57, 74) (57, 90) (62, 66) (62, 89) (66, 89)
 (67, 76) (67, 91) (71, 92) (71, 99) (74, 90) (92, 99)]
(30,)


In [31]:
#74
A = np.random.randint(0, 10, (100))
C = np.bincount(A)
A_ = np.repeat(np.arange(len(C)), C)
print(np.bincount(A))
print(np.bincount(A_))


[10  9  5  7 17 10 11 10  8 13]
[10  9  5  7 17 10 11 10  8 13]


In [53]:
#75

n = 3
A = np.arange(20)
B = np.cumsum(A, dtype=float)
B[n:] = B[n:] - B[:-n]
print(B[n-1:]/n)


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [64]:
#76

from numpy.lib.stride_tricks import sliding_window_view
n=3
A = np.arange(20)
B = sliding_window_view(A, 3)
print(B)

[[ 0  1  2]
 [ 1  2  3]
 [ 2  3  4]
 [ 3  4  5]
 [ 4  5  6]
 [ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]
 [ 9 10 11]
 [10 11 12]
 [11 12 13]
 [12 13 14]
 [13 14 15]
 [14 15 16]
 [15 16 17]
 [16 17 18]
 [17 18 19]]


In [82]:
#77
A = np.random.uniform(0, 5, (4, 4))
B = np.random.randint(0, 5, (4, 4))


#for float
A_not = np.negative(A)
B_not = np.negative(B)

#for boolean
B_logic_not = np.logical_not(B)

print(B)
print(B_not)
print(B_logic_not)

[[1 2 3 2]
 [0 4 4 2]
 [1 0 1 0]
 [1 0 4 0]]
[[-1 -2 -3 -2]
 [ 0 -4 -4 -2]
 [-1  0 -1  0]
 [-1  0 -4  0]]
[[False False False False]
 [ True False False False]
 [False  True False  True]
 [False  True False  True]]


In [96]:
#78

def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10, 10, (10, 2))
P1 = np.random.uniform(-10, 10, (10, 2))
p = np.random.uniform(-10, 10, (1, 2))

distance(P0, P1, p)

array([13.21157078, 10.22729073,  3.73406405,  0.46802283,  4.96486716,
        9.34109834,  0.42838135,  0.63928263,  7.38257216,  7.20494073])

In [97]:
#79

def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10, 10, (10, 2))
P1 = np.random.uniform(-10, 10, (10, 2))
p = np.random.uniform(-10, 10, (10, 2))

print(np.array([distance(P0, P1, p[i, :]) for i in range(10)])) 

[[5.14686822e+00 2.71381957e+00 9.85391177e+00 3.20767966e+00
  1.86815518e+00 9.27297986e-01 1.03900501e+01 2.29990750e+00
  1.25866644e+01 6.24935517e+00]
 [9.90610187e+00 1.94941199e+00 5.01930122e+00 5.95482837e+00
  2.91141563e+00 2.85790281e+00 5.16219616e+00 6.28640814e+00
  7.25721725e+00 1.32106028e+00]
 [3.78982524e+00 3.51133434e+00 1.07215336e+01 3.03998009e+00
  3.22619137e+00 2.16415855e-02 1.14471954e+01 1.01480140e+00
  1.39204389e+01 7.15757034e+00]
 [8.70557926e+00 5.72362138e+00 1.24762567e+01 2.25384494e+00
  1.64709324e+00 7.23531044e+00 1.17734885e+01 7.09252094e+00
  1.08706047e+01 8.63219267e+00]
 [8.30244839e+00 3.23005285e+00 3.91023929e+00 8.32841655e+00
  1.32666435e+00 7.19876002e-02 4.60041617e+00 4.14782283e+00
  8.05694558e+00 3.17953609e-01]
 [1.11477469e+01 4.56575533e+00 2.41411549e+00 8.29082327e+00
  4.17100703e+00 2.31352727e+00 2.65798997e+00 6.93611311e+00
  5.37793761e+00 1.27205718e+00]
 [2.27308308e+01 6.40482568e+00 2.21652993e-01 3.97486110e

In [98]:
#80

Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.full(shape, fill, dtype=Z.dtype)
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices