In [1]:
#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [2]:
import numpy as np

In [11]:
#61

z = np.random.uniform(0, 10, (3, 4))
given_value = 5.55
print(z)
diff = z - given_value
nearest_idx = np.argmin(np.abs(diff))
z[np.unravel_index(nearest_idx, z.shape)]

[[2.67952215 7.50925142 0.6057732  3.3893961 ]
 [9.35177461 9.51718957 7.10009676 2.74230876]
 [9.35761067 8.19060813 3.25040362 5.56161088]]


5.5616108786746485

In [21]:
#62
a = np.random.rand(1, 3)
b = np.random.rand(3, 1)
it = np.nditer([a, b, None])

print(a, b)

for x, y, z in it:
    z[...] = x + y
print(it.operands[2])

[[0.60610538 0.59899433 0.56502029]] [[0.19217073]
 [0.91228524]
 [0.45420258]]
[[0.79827611 0.79116506 0.75719102]
 [1.51839062 1.51127957 1.47730553]
 [1.06030796 1.05319691 1.01922286]]


In [43]:
#63

class NamedArray(np.ndarray):

    def __new__(subtype, shape, dtype=float, buffer=None, offset=0,
                strides=None, order=None, name=None):
        obj = super().__new__(subtype, shape, dtype, buffer, offset, strides, order)
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'info', None)

n = NamedArray(shape=(3,), name="array_chan")
print(n.name)


class NamedArray2(np.ndarray):

    def __new__(cls, array_, name=None):
        obj = np.asarray(array_).view(cls)
        obj.name = name
        return obj
    
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'info', None)

n2 = NamedArray2(np.arange(3), "array_kun")
print(n2.name)

array_chan
array_kun


In [76]:
#64

#soln1
z = np.random.uniform(0, 20, (4, 5))
ones = np.ones_like(z)
x, y = z.shape

add_places = 5
add_idx1 = np.random.randint(0, x, (add_places, 1))
add_idx2 = np.random.randint(0, x, (add_places, 1))
add_idx = np.concatenate([add_idx1, add_idx2], axis=-1)

#soln1 ignores repeated indices
# z[add_idx1, add_idx2] += 1
# print(z)

#soln2 best solution
z = np.random.uniform(0, 20, (4, 5))
np.add.at(z, add_idx, 1)
print(z)

#soln3 for 1d arrays
# z = np.random.uniform(0, 20, (20))
# indices = np.random.randint(0, 20, 10)
# z+=np.bincount(indices, minlength=20)
# print(z)

[[ 4.03971227 13.93214355 14.95071211  2.15778468 15.70152771]
 [ 8.83705068  8.2596909   6.06038863 16.203841   17.44152139]
 [ 6.65075754 21.85336401 11.60908341 22.52992419 21.69857083]
 [23.40050319  6.61799072 21.07637252 17.84460859  6.59499275]]


In [83]:
#65
x = np.random.randint(0, 10, 10)
indices = np.random.randint(0, 20, 10)
print(x)
print(indices)
np.bincount(indices, weights=x)

[4 8 2 5 4 4 5 6 6 6]
[10  8 12  6 19 15 10 10  1 10]


array([ 0.,  6.,  0.,  0.,  0.,  0.,  5.,  0.,  8.,  0., 21.,  0.,  2.,
        0.,  0.,  4.,  0.,  0.,  0.,  4.])

In [113]:
#66
w, h = 10, 9
shape_ = (w, h, 3)
image = np.random.randint(0, 4, shape_).astype(np.ubyte)
print(np.unique(image.reshape(-1, 3), axis=0).shape)

(47, 3)


In [123]:
#67

z = np.random.rand(2, 3, 4, 5)
print(z.sum(axis=(-1, -2)))
print(z.sum(axis=(-2, -1)))

[[ 9.50425245 11.29749312  9.27709638]
 [ 7.27106     9.88854223  9.12009483]]
[[ 9.50425245 11.29749312  9.27709638]
 [ 7.27106     9.88854223  9.12009483]]


In [16]:
#68

z = np.random.randint(0, 10, 50)
i = np.random.randint(0, 10, 50)
d = np.bincount(i, z)
b = np.bincount(i)
print(d/b)

[5.         2.125      4.66666667 5.         3.         4.5
 6.5        4.         3.66666667 4.625     ]


In [20]:
#69

a = np.random.rand(3, 4)
b = np.random.rand(4 , 3)

#soln1
print(np.diag(np.dot(a, b)))

#soln2
prod = a * b.T
print(np.sum(prod, axis=1))

[1.088476   1.57226906 0.61247358]
[1.088476   1.57226906 0.61247358]


In [23]:
#70
inp = np.arange(5)+1
z = np.zeros(5+4*3)
z[::4] = inp
z

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])