In [1]:
#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)
#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)
#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?
#### 54. How to read the following file? (★★☆)
#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)
#### 56. Generate a generic 2D Gaussian-like array (★★☆)
#### 57. How to randomly place p elements in a 2D array? (★★☆)
#### 58. Subtract the mean of each row of a matrix (★★☆)
#### 59. How to sort an array by the nth column? (★★☆)
#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [2]:
import numpy as np

In [4]:
#51
pixel_dtype = np.dtype([
                        ('position', 
                                        [('X', np.float32), 
                                        ('Y', np.float32)]
                        ), 
                        ('color', 
                                        [('R', np.uint8),
                                        ('G', np.uint8),
                                        ('B', np.uint8)]
                        )
                    ])

In [19]:
#52
z = np.random.uniform(-10, 10, (2, 2))

#soln1
x, y = z[:, 0], z[:, 1]
x_ = np.subtract.outer(x, x)**2
y_ = np.subtract.outer(y, y)**2
dist = np.sqrt(x_+y_)
print(dist, end='\n\n')

#soln2
x, y = np.atleast_2d(z[:,0], z[:,1])
dist = np.sqrt( (x-x.T)**2 + (y-y.T)**2)
print(dist)

[[0.         3.74058065]
 [3.74058065 0.        ]]

[[0.         3.74058065]
 [3.74058065 0.        ]]


In [26]:
#53

z = np.random.uniform(-10, 10, 10).astype(np.float32)

#soln1 actually converts float value to int
# z[:] = z.astype(np.int32)

#soln2 just reads the underlying data as int32
z = z.view(np.int32)
print(z)

[-1058681368  1088780838  1088589638 -1062750558  1090638557  1068998498
 -1063767085 -1058294374  1076885211  1072951881]


In [32]:
#54

# file_contents = "1, 2, 3, 4, 5\n6,  ,  , 7, 8\n,  , 9,10,11"
z = np.genfromtxt(open("54.txt"), delimiter=',', missing_values=np.nan)
z

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6., nan, nan,  7.,  8.],
       [nan, nan,  9., 10., 11.]])

In [38]:
#55
z = np.random.uniform(-10, 10, (2, 3))
for i, elem in np.ndenumerate(z):
    print(i, elem)

for i in np.ndindex(3, 2):
    print(i)

(0, 0) -9.019563713069637
(0, 1) 3.43899617157871
(0, 2) -9.793314254848331
(1, 0) -8.109434107983976
(1, 1) -5.485135197047932
(1, 2) -7.60610126092891
(0, 0)
(0, 1)
(1, 0)
(1, 1)
(2, 0)
(2, 1)


In [14]:
#56

np.set_printoptions(precision=4)
#soln1
x = np.random.normal(0, 1, size=(5))
x = np.sort(x)
y = x
x, y = np.meshgrid(x, y)
g = x+y
print(g)


#soln2
X, Y = np.meshgrid(np.linspace(-1,1,5), np.linspace(-1,1,5))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[-5.3871 -3.898  -2.9612 -2.4644 -1.7626]
 [-3.898  -2.4089 -1.4721 -0.9753 -0.2735]
 [-2.9612 -1.4721 -0.5353 -0.0385  0.6633]
 [-2.4644 -0.9753 -0.0385  0.4583  1.1601]
 [-1.7626 -0.2735  0.6633  1.1601  1.862 ]]
[[0.3679 0.5353 0.6065 0.5353 0.3679]
 [0.5353 0.7788 0.8825 0.7788 0.5353]
 [0.6065 0.8825 1.     0.8825 0.6065]
 [0.5353 0.7788 0.8825 0.7788 0.5353]
 [0.3679 0.5353 0.6065 0.5353 0.3679]]


In [81]:
#57
import random
p = 3
z = np.random.uniform(0, 10, (3, 4))
np.put(z, random.choices(range(100), k=p), 10, mode='clip')
print(z)


[[ 0.7428  9.2175  1.5765  7.8799]
 [ 9.8349 10.      7.4093  8.654 ]
 [ 5.0644  3.7619  6.761  10.    ]]


In [92]:
#58

z = np.random.uniform(0, 10, (3, 4))
#soln1
means = np.expand_dims(np.mean(z, axis=-1), axis=1)
#soln2
means = z.mean(axis=1, keepdims=True)

print(z)
print(means)
print(np.subtract(z, means))


[[8.5288 7.5117 8.193  3.779 ]
 [8.1965 1.9375 7.9449 2.4365]
 [3.8258 9.9173 7.2379 4.6145]]
[[7.0031]
 [5.1288]
 [6.3989]]
[[ 1.5257  0.5086  1.1899 -3.2241]
 [ 3.0677 -3.1913  2.8161 -2.6924]
 [-2.573   3.5184  0.839  -1.7844]]


In [96]:
#59

z = np.random.uniform(0, 10, (3, 4))
print(z[z[:, 1].argsort()])

[[2.4566 3.73   4.4848 9.0064]
 [8.1633 9.3197 6.139  5.6764]
 [5.2034 9.7409 0.3082 1.6212]]


In [125]:
#60

z = np.random.randint(0, 2, (3, 4))
print(z)
(~z.any(axis=0)).any()

[[0 0 1 0]
 [1 1 1 0]
 [0 1 0 0]]


True