In [1]:
#### 11. Create a 3x3 identity matrix (★☆☆)

#### 12. Create a 3x3x3 array with random values (★☆☆)

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

#### 17. What is the result of the following expression? (★☆☆)

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [11]:
import numpy as np

In [5]:
#11
z = np.eye(3, 3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
#12
z = np.random.rand(3, 3, 3)
print(z)

[[[0.89647423 0.39691775 0.14862886]
  [0.72093848 0.88250168 0.20447917]
  [0.28132551 0.4503373  0.28779126]]

 [[0.60137763 0.59144868 0.40746535]
  [0.25780388 0.71843094 0.59153773]
  [0.79294075 0.80109724 0.29935591]]

 [[0.50576526 0.16607715 0.43945797]
  [0.79940841 0.69422557 0.2105742 ]
  [0.09871896 0.15853127 0.23474447]]]


In [10]:
#13
z = np.random.uniform(3, 30, (3, 3))
print(np.max(z), np.min(z))

29.8088683244343 8.365510000936782


In [12]:
#14
z = np.random.rand(30)
print(np.mean(z))

0.4805185432948436


In [30]:
#15
z = np.full((5, 5), 1)
z[1:-1, 1:-1] = 0
print(z)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [41]:
#16
z = np.zeros((6, 6))
print(np.pad(z, 1, 'constant', constant_values=1))
z[:, [0, -1]] = 1
z[[0, -1], :] = 1
print(z)


[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [48]:
#17

print(0 * np.nan) #np.nan
print(np.nan == np.nan) #False
print(np.inf > np.nan) #False
print(np.nan - np.nan) #np.nan
print(np.nan in set([np.nan])) #true
print(0.3 == 3 * 0.1) #false

nan
False
False
nan
True
False


In [56]:
#18

z = np.arange(1, 5)
print(z.shape)
z = np.diag(z, k=-1)
z

(4,)


array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [75]:
#19

#soln1
z = np.tile([[0., 1],[1, 0]], (4, 4))
print(z)

#soln2
# z = np.zeros((8, 8))
# z[1::2, ::2] = 1
# z[::2, 1::2] = 1
# print(z)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [83]:
#20

z = np.zeros((6, 7, 8))
np.unravel_index(99, (z.shape))

(1, 5, 3)