In [1]:
#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [2]:
import numpy as np
np.set_printoptions(precision=4)

In [3]:
#81
from numpy.lib.stride_tricks import sliding_window_view

Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]
print(sliding_window_view(Z, 4))

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [16]:
#82
z = np.random.uniform(0, 10, (6, 15))

#soln1
print(np.linalg.matrix_rank(z))

#soln2
x, a, y = np.linalg.svd(z)
print(np.sum(a > 1e-10))

6
6


In [22]:
#83

z = np.random.randint(0, 20, 10)
print(z)

#soln1
uniq_counts = np.unique(z, return_counts=True)
uniq, counts = uniq_counts
freq_idx = np.argmax(counts)
print(uniq[freq_idx])

#soln2
bins = np.bincount(z)
print(np.argmax(bins))

[14  9  6  4  5  7 14  8  2  3]
14
14


In [26]:
#84

from numpy.lib.stride_tricks import sliding_window_view

z = np.random.rand(10, 10)
win_shape = (3, 3)
# print(z)
new_view = sliding_window_view(z, win_shape)

In [43]:
#85

class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)


[[ 3  7  7  5  4]
 [ 7  4  8 11  7]
 [ 7  8  6 42 12]
 [ 5 11 42  1 10]
 [ 4  7 12 10  1]]


In [11]:
#86

a = np.arange(32).reshape(2, 4, 4)
b = np.arange(8).reshape(2, 4, 1)
# print(a)
# print(b)
# print(np.matmul(a, b))
print(np.tensordot(a, b, axes=[[0, 2], [0, 1]]))

[[404]
 [516]
 [628]
 [740]]


In [31]:
#87
from numpy.lib.stride_tricks import sliding_window_view
z = np.random.rand(16, 16)
win_shape = (4, 4)

slides = sliding_window_view(z, win_shape)
print(slides.shape)
print(sliding_window_view(z, window_shape=win_shape)[::4, ::4].sum(axis=(-2, -1)))

(13, 13, 4, 4)
[[ 6.3855  8.067   9.2165  8.2069]
 [ 7.9368  7.7051  9.7577  8.3464]
 [10.4335  7.9619  8.6155  7.2826]
 [ 8.2315  6.6546  7.8759  6.852 ]]


In [ ]:
#88



In [60]:
#89

z = np.arange(100)
np.random.shuffle(z)
k = 5

#soln1
top_k_indices = np.argsort(-z)[:k]
# print(top_k_indices)
print(z[top_k_indices][:k])

#soln2
print(z[np.argpartition(-z, k)[:k]])

[99 98 97 96 95]
[98 99 97 96 95]


In [63]:
#90

def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]
