In [1]:
#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)
#### 32. Is the following expressions true? (★☆☆)
#python
#np.sqrt(-1) == np.emath.sqrt(-1)
#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)
#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)
#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)
#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)
#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
#### 40. Create a random vector of size 10 and sort it (★★☆)

In [2]:
import numpy as np

In [3]:
#31
defaults = np.seterr(all="warn")
_ = np.seterr(**defaults)

In [4]:
#32
np.sqrt(-1) == np.emath.sqrt(-1)
print(np.sqrt(-1))
print(np.emath.sqrt(-1))

nan
1j


/var/folders/zw/8cs3hp9s53q_p69tftz7xhwr0000gq/T/ipykernel_82445/3979951725.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)
/var/folders/zw/8cs3hp9s53q_p69tftz7xhwr0000gq/T/ipykernel_82445/3979951725.py:3: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))


In [5]:
#33

today_date = np.datetime64('today')
yesterday_date = np.datetime64('today') - np.timedelta64(1, 'D')
tomorrow_date = np.datetime64('today') + np.timedelta64(1, 'D')
print("today", today_date)
print("yesterday", yesterday_date)
print("tomorrow", tomorrow_date)

today 2023-04-09
yesterday 2023-04-08
tomorrow 2023-04-10


In [6]:
#34
jul_2016 = np.datetime64("2016-07-01")
aug_2016 = np.datetime64("2016-08-01")

np.arange(jul_2016, aug_2016, dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [7]:
#35
a = np.random.uniform(-10, 10, (4, 5))
b = np.random.uniform(-10, 10, (4, 5))
np.add(a, b, out=b)
np.negative(a, out=a)
np.divide(a, 2, out=a)
np.multiply(b, a, out=a)
print(a)

[[ 2.34286356e+00  6.16180161e+00  3.94192295e+00 -3.95081368e+01
  -2.61978552e+01]
 [-8.89046779e+00 -1.92956802e+01 -2.28789006e+01 -1.98615807e+01
  -8.30580592e+01]
 [-1.83716168e+00  3.28597407e+00  6.61880602e+00 -1.35623550e+01
  -9.31882427e+00]
 [-8.57309912e+01 -3.79187527e+01  1.73723613e-02  2.99162245e-02
  -4.09270741e+01]]


In [9]:
#36

z = np.random.uniform(-10, 10, (2, 5))
print(z)

#soln1
print(np.where(z<0, np.ceil(z), np.floor(z)))

#soln2
print(z.astype(np.int64))

#soln3
print(np.trunc(z))

#these solution only work with positive values
#soln4
# print(z - z%1)
#soln5
# print(z//1)
#soln6
# print(np.floor(z))

[[ 9.4867757   8.65322559  3.73298737 -4.90449036 -5.96688594]
 [ 7.3441976  -3.21531525  5.12689568 -4.42088254 -0.62506358]]
[[ 9.  8.  3. -4. -5.]
 [ 7. -3.  5. -4. -0.]]
[[ 9  8  3 -4 -5]
 [ 7 -3  5 -4  0]]
[[ 9.  8.  3. -4. -5.]
 [ 7. -3.  5. -4. -0.]]


In [18]:
#37
z = np.arange(5)
z = np.expand_dims(z, 0)
z = np.repeat(z, 5, axis=0)
print(z)

z_ = np.zeros((5, 5))
z_ += np.arange(5)
print(z_)


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [27]:
#38
import random

def int_generator():
    for _ in range(10):
        yield random.randint(0, 10)

np.fromiter(int_generator(),  np.int)

/var/folders/zw/8cs3hp9s53q_p69tftz7xhwr0000gq/T/ipykernel_82694/2110699626.py:8: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.fromiter(int_generator(),  np.int)


array([ 1,  8,  0,  6,  2,  0, 10,  0,  0,  9])

In [37]:
#39

z = np.linspace(0, 1, 11, endpoint=False)[1:]
z

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [49]:
#40

z = np.random.uniform(-10, 10, 10)

#soln1
# z = np.sort(z)
# print(z)

#soln2
z.sort()
print(z)

#soln3 returns list
# z = sorted(z)
# print(type(z), z)

[-9.39834917 -8.69589824 -4.10203398 -3.73172475 -2.34369772 -1.59599183
  3.49390508  6.55636314  8.01540656  9.15983197]
