In [1]:
#### 41. How to sum a small array faster than np.sum? (★★☆)
#### 42. Consider two random array A and B, check if they are equal (★★☆)
#### 43. Make an array immutable (read-only) (★★☆)
#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)
#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)
#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)
#### 49. How to print all the values of an array? (★★☆)
#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [3]:
import numpy as np

In [55]:
#41

z = np.random.uniform(0, 10, 200)

In [59]:
%time
np.sum(z)

CPU times: user 4 µs, sys: 1e+03 ns, total: 5 µs
Wall time: 8.82 µs


1002.2459520396642

In [60]:
%time
np.add.reduce(z)

CPU times: user 3 µs, sys: 1 µs, total: 4 µs
Wall time: 6.91 µs


1002.2459520396642

In [61]:
%time
sum(z)

CPU times: user 2 µs, sys: 1 µs, total: 3 µs
Wall time: 5.72 µs


1002.2459520396637

In [67]:
#42
a = np.random.uniform(0, 10, (4, 5))
b = np.random.uniform(0, 10, (4, 5))

#soln1
print(np.array_equal(a, b))

#soln2
print(np.allclose(a, b))

False
False


In [69]:
#43

z = np.random.rand(4, 5)
z.flags.writeable = False
z[0] = 1 #ValueError

ValueError: assignment destination is read-only

In [89]:
#44

z_carte  = np.random.uniform(-10, 10, (10, 2))
x, y = z_carte[:, 0], z_carte[:, 1]
print(z_carte)

r = np.expand_dims(np.sqrt(x**2 + y**2), axis=1)
theta = np.expand_dims(np.arctan(y/x), axis=1)

z_polar = np.concatenate([r, theta], axis=-1)
print(z_polar)

[[-1.74314455 -2.62244066]
 [-3.8647911   0.41201101]
 [-5.70540693 -2.94549425]
 [ 0.5089293   8.93544835]
 [ 5.03786574 -5.47529385]
 [-1.56001322 -6.51432397]
 [ 0.99760828 -7.71341762]
 [ 9.45389041  6.2652983 ]
 [-2.14998066 -4.12709879]
 [ 5.30902951  0.57931209]]
[[ 3.14892806  0.98415432]
 [ 3.88669053 -0.10620516]
 [ 6.42087257  0.47657372]
 [ 8.94992996  1.51390158]
 [ 7.44035846 -0.82698185]
 [ 6.69851163  1.33574847]
 [ 7.77766248 -1.44217617]
 [11.34151695  0.5852665 ]
 [ 4.65353212  1.09053552]
 [ 5.34054275  0.10868825]]


In [95]:
#45

z = np.random.uniform(-10, 10, 10)
print(z)
z[np.argmax(z)] = 0
print(z)


[-0.10440592  6.99065358  3.8059948  -9.84686849  5.76586007  9.48892727
  0.36424121 -8.89626677 -3.87497097  8.6444331 ]
[-0.10440592  6.99065358  3.8059948  -9.84686849  5.76586007  0.
  0.36424121 -8.89626677 -3.87497097  8.6444331 ]


In [108]:
#46

new_dtype = np.dtype([('X', np.float), ('Y', np.float)])
Z = np.zeros((5, 5), dtype=new_dtype)
x = np.linspace(0, 1, 5)
y = np.linspace(0, 1, 5)
Z['X'], Z['Y'] = np.meshgrid(x, y)
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


/var/folders/zw/8cs3hp9s53q_p69tftz7xhwr0000gq/T/ipykernel_83913/538764345.py:3: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  new_dtype = np.dtype([('X', np.float), ('Y', np.float)])


In [127]:
#47

X = np.random.uniform(-10, 10, 2)
Y = np.random.uniform(-10, 10, 2)
denom = np.subtract.outer(X, Y)
print(1/denom)

[[ 0.27396198  0.48689815]
 [-0.28535482 -0.19605026]]


In [143]:
#48
print(np.iinfo(np.int8).max)
print(np.iinfo(np.int8).min)

print(np.finfo(np.float16).max)
print(np.finfo(np.float16).min)
print(np.finfo(np.float16).eps)

127
-128
65500.0
-65500.0
0.000977


In [151]:
#49
z = np.random.rand(2, 2)
print(z)
np.set_printoptions(precision=4)
print(z)

[[0.93377769 0.8806311 ]
 [0.77477656 0.1231183 ]]
[[0.9338 0.8806]
 [0.7748 0.1231]]


In [202]:
#50

find_value = 4.5353
z = np.random.uniform(0, 10, (4, 5))
print(z)
z_diff = z - find_value
closest_idx = np.argmin(np.abs(z_diff))
closest_idx = np.unravel_index(closest_idx, (4, 5))
print(z[closest_idx])

[[5.0493 3.6109 2.7412 9.0031 3.0326]
 [7.978  6.575  4.8438 5.6496 4.6679]
 [1.4061 2.3744 2.383  3.4952 1.1405]
 [1.0491 8.7253 5.7038 2.0077 7.2101]]
4.667884681555611
