In [3]:
#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
#### 22. Normalize a 5x5 random matrix (★☆☆)
#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
#### 26. What is the output of the following script? (★☆☆)
#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
#### 28. What are the result of the following expressions? (★☆☆)
#### 29. How to round away from zero a float array ? (★☆☆)
#### 30. How to find common values between two arrays? (★☆☆)

In [2]:
import numpy as np

In [4]:
#21
z = np.tile([[0., 1],[1, 0]], (4, 4))
print(z)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [15]:
#22
z = np.random.rand(5, 5)
print((z - z.mean())/z.std())

[[ 2.00958     0.60516363  0.87566481 -0.17296059 -0.56440045]
 [ 0.83554692 -2.15340781 -0.33198012 -0.40634634 -1.34665198]
 [-0.16025678  1.38975426  1.15033895  0.05223604 -2.23470009]
 [ 0.13832373  0.13120391  0.61200013 -0.76120122  0.66712233]
 [-0.77534843  1.04651117  0.12483068 -0.79242789  0.06140515]]


In [16]:
#23
color_dt = np.dtype([("R", np.uint8), ("G", np.uint8), ("B", np.uint8), ("A", np.float64)])

In [19]:
#24

a = np.random.rand(5, 3)
b = np.random.rand(3, 2)

#soln1
print(np.matmul(a, b))

#soln2
print(np.dot(a, b))

[[0.42452813 0.30776195]
 [0.32884905 0.30991472]
 [0.81767762 0.68310784]
 [1.23542445 1.4049188 ]
 [1.17760027 1.71631248]]
[[0.42452813 0.30776195]
 [0.32884905 0.30991472]
 [0.81767762 0.68310784]
 [1.23542445 1.4049188 ]
 [1.17760027 1.71631248]]


In [20]:
#25

z = np.random.randint(1, 10, (10))
print(z)
z[(z>3) & (z<8)] *= -1
print(z)

[1 1 3 5 9 6 4 5 8 7]
[ 1  1  3 -5  9 -6 -4 -5  8 -7]


In [1]:
#26

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


In [5]:
#27
Z = np.random.randint(0, 10, 10)
print(Z**Z)
print(2 << Z >> 2)
Z = np.random.randint(-10, 10, 10)
print(Z)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
# print(Z<Z>Z) # nor a valid expression

[387420489     46656      3125         1         1      3125         4
 387420489        27       256]
[256  32  16   1   1  16   2 256   4   8]
[  3  -8   7  -4   4   6 -10  -1   2   9]
[False  True False  True False False  True  True False False]
[ 0. +3.j -0. -8.j  0. +7.j -0. -4.j  0. +4.j  0. +6.j -0.-10.j -0. -1.j
  0. +2.j  0. +9.j]
[  3.  -8.   7.  -4.   4.   6. -10.  -1.   2.   9.]


In [14]:
#28

print(np.array(0) / np.array(0)) #np.nan
print(np.array(0) // np.array(0)) #0
print(np.array([np.nan]).astype(int).astype(float32))
print(np.array([0]).astype(np.float32))


nan
0
[-9.223372e+18]
[0.]


/var/folders/zw/8cs3hp9s53q_p69tftz7xhwr0000gq/T/ipykernel_80988/1652630034.py:3: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0)) #np.nan
/var/folders/zw/8cs3hp9s53q_p69tftz7xhwr0000gq/T/ipykernel_80988/1652630034.py:4: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0)) #0


In [7]:
#29

z = np.random.uniform(-10, 10, (4, 5))
print(z)

#soln1
z1 = np.where(z<0, np.floor(z), np.ceil(z))
print(z1)

#soln2
z2 = np.copysign(np.ceil(np.abs(z)), z)
print(z2)

[[ 2.80481466 -4.7593439  -0.33355068  4.43148888  2.71097107]
 [ 9.73881533  1.9836489  -6.64114573  0.82891965  2.68739032]
 [ 8.03861847  2.86519744 -7.02529058 -3.85045347 -9.37344089]
 [-2.35436461  8.90858767 -3.1043947  -9.01091087  2.11128731]]
[[  3.  -5.  -1.   5.   3.]
 [ 10.   2.  -7.   1.   3.]
 [  9.   3.  -8.  -4. -10.]
 [ -3.   9.  -4. -10.   3.]]
[[  3.  -5.  -1.   5.   3.]
 [ 10.   2.  -7.   1.   3.]
 [  9.   3.  -8.  -4. -10.]
 [ -3.   9.  -4. -10.   3.]]


In [35]:
#30

z = np.random.randint(0, 15, 5)
z_ = np.random.randint(0, 15, 5)
print(z)
print(z_)
print(np.intersect1d(z, z_))

[ 7  5  9 10  4]
[13  1 14  4 14]
[4]
