In [1]:
#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [60]:
import numpy as np
np.set_printoptions(precision=4)

In [15]:
#71
a = np.ones((5, 5, 3))
b = 2*np.ones((5, 5))
print(b)

print(a * b[:,:, None])

[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]
[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [20]:
#72
z = np.arange(12).reshape(3, 4)
z[[0, 1]] =  z[[1, 0]]
z

array([[ 4,  5,  6,  7],
       [ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [21]:
#73


In [32]:
#74
C = np.random.randint(0, 5, (10))
elems = np.arange(C.shape[0])
A = np.repeat(elems, C)
print(A)

[0 0 1 1 1 2 2 2 3 3 3 3 4 5 5 6 6 6 7 7 8 8 9 9 9]


In [57]:
#75
from numpy.lib.stride_tricks import sliding_window_view

win_size = 3
Z = np.arange(20)
cumsum_ = np.cumsum(Z)
#soln1
rolling_sum = cumsum_[win_size:] - cumsum_[:cumsum_.shape[0]-win_size]
print(rolling_sum/3)

#soln2
slidings = sliding_window_view(Z, win_size)
sum_ = np.sum(slidings, axis=1)
print(sum_/win_size)

[ 2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [58]:
#76

from numpy.lib.stride_tricks import sliding_window_view

win_size = 3
Z = np.arange(20)
print(sliding_window_view(Z, win_size))

[[ 0  1  2]
 [ 1  2  3]
 [ 2  3  4]
 [ 3  4  5]
 [ 4  5  6]
 [ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]
 [ 9 10 11]
 [10 11 12]
 [11 12 13]
 [12 13 14]
 [13 14 15]
 [14 15 16]
 [15 16 17]
 [16 17 18]
 [17 18 19]]


In [68]:
#77

z = np.random.uniform(-10, 10, (3, 4))
print(z)
np.negative(z, out=z)
print(z)

z_ = np.random.randint(0, 2, (3, 4)).astype(np.bool8)
print(z_)
np.logical_not(z_, out=z_)
print(z_)

[[-9.696  -4.9309 -1.349   6.32  ]
 [-0.0304  3.5714  2.8562 -1.85  ]
 [-7.9114 -0.9086 -7.0842  5.1529]]
[[ 9.696   4.9309  1.349  -6.32  ]
 [ 0.0304 -3.5714 -2.8562  1.85  ]
 [ 7.9114  0.9086  7.0842 -5.1529]]
[[False False  True  True]
 [ True  True False False]
 [False False False  True]]
[[ True  True False False]
 [False False  True  True]
 [ True  True  True False]]


In [73]:
#78

def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))


[7.3817 9.5381 3.5766 9.8432 4.7178 2.0845 0.3593 1.6612 3.7565 9.167 ]


In [75]:
#79
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[10.7745  3.9662  4.4573  3.1648  2.0026 12.9727  8.0031  8.3389 11.208
   3.0708]
 [ 6.7905  0.8699  1.1438  2.1764  3.5558 10.7694  3.9795  9.2506  9.4776
   3.9663]
 [ 2.5569  7.055   0.0357  3.7147  3.9253  2.2559 15.3544  5.6006  4.1428
  10.8875]
 [ 1.6285  4.568   1.2762  0.0687  4.4534  4.0062  9.1221  1.979   2.4791
   3.3087]
 [ 6.9099  1.9986  6.5807  7.7046  3.2971  6.6902 15.0834  0.2581  4.4848
   5.007 ]
 [ 5.3887  3.2833  5.0898  6.5968  7.2594 11.0779  0.3072 11.9149 10.1876
   6.6201]
 [ 3.4593  8.2015  1.3747  2.3226  5.3098  2.6773 14.2371  5.226   4.4402
  10.517 ]
 [ 2.4148  9.0469  5.7697  3.82    9.0407  1.117   6.7696  1.4915  0.072
   3.8097]
 [ 1.5547  7.273   8.6368  9.3657 10.9775  7.9464  1.5001 10.6055  7.2918
   5.2996]
 [ 0.8754  6.4598  1.6122  0.808   5.1292  0.8748 11.2214  1.2257  0.7341
   6.5157]]


In [89]:
#80
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill #(5, 5) all 0s
P  = np.array(list(position)).astype(int) #[1 1] (2)
Rs = np.array(list(R.shape)).astype(int)#[5 5]
Zs = np.array(list(Z.shape)).astype(int)#[10 10]

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices