In [5]:
#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [2]:
import numpy as np
np.set_printoptions(precision=4)

In [14]:
#91
z = np.array(['Vipul', 26, 58.5, 174.9])
record = np.core.records.fromarrays(z, dtype=[('name', 'S25'), ('age', 'u1'), ('weight', 'f2'), ('height', 'f2')])
record

rec.array((b'Vipul', 26, 58.5, 174.9),
          dtype=[('name', 'S25'), ('age', 'u1'), ('weight', '<f2'), ('height', '<f2')])

In [22]:
#92

z = np.random.uniform(-10, 10, (1000))

#soln1
%timeit z_cube1 = z**3

#soln2
pow = np.full_like(z, 3)
%timeit z_cube2 = np.power(z, pow)

#soln3
%timeit np.einsum('i,i,i->i', z, z, z)

25.2 µs ± 286 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
23.6 µs ± 419 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
4.01 µs ± 10 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [53]:
#93

a = np.random.randint(0, 10, (8, 3))
b = np.random.randint(0, 5, (2, 2))


c = a[..., np.newaxis, np.newaxis] == b
rows = np.where(c.any((3, 1)).all(1))[0]
print(rows, a[rows])

[1 6] [[4 1 4]
 [4 2 0]]


In [95]:
#94

z = np.random.randint(0, 2, (10, 3))
print(z)
z1 = np.expand_dims(z, -1)
z1 = np.repeat(z1, 3, axis=-1)
z2 = np.expand_dims(z, -2)
z2 = np.repeat(z2, 3, axis=-2)
# print(z2)
c = z1 == z2
# print(c.all((2, 1)))
diff_rows = np.where(~c.all((2, 1)))
print(diff_rows)
print(z[diff_rows])

[[1 1 0]
 [0 0 0]
 [1 0 1]
 [0 1 0]
 [1 1 0]
 [1 1 1]
 [0 0 1]
 [1 1 0]
 [1 0 1]
 [1 1 0]]
(array([0, 2, 3, 4, 6, 7, 8, 9]),)
[[1 1 0]
 [1 0 1]
 [0 1 0]
 [1 1 0]
 [0 0 1]
 [1 1 0]
 [1 0 1]
 [1 1 0]]


In [107]:
#95

z = np.random.randint(0, 10, 10, dtype=np.uint8)
z = np.unpackbits(z[..., np.newaxis], axis=1)
z

array([[0, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 1, 1, 0]], dtype=uint8)

In [146]:
#96

z = np.random.randint(0, 2, (10, 3))
print(z)
z = np.unique(z, axis=0)
print(z)

# np.where(c.all(2))

[[1 0 1]
 [1 1 0]
 [1 1 0]
 [1 0 1]
 [1 1 0]
 [1 1 0]
 [0 1 1]
 [0 1 1]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 1 1]
 [1 0 1]
 [1 1 0]]


In [89]:
#97

a = np.random.randint(-10, 10, (10))
b = np.random.randint(-10, 10, (10))
print(a)
print(b)
#vector product
print(np.einsum('j, i -> ij', a, b))
#sum
print(np.einsum('ij->j', [a, b]))
#multiply
print(np.einsum('i, i->i', a, b))
#dot
print(np.einsum('i, i->', a, b))

[-10   8   8  -7   2  -5   3  -1   7   6]
[ 6  1  8 -8  6 -9  4  5  1 -5]
[[-60  48  48 -42  12 -30  18  -6  42  36]
 [-10   8   8  -7   2  -5   3  -1   7   6]
 [-80  64  64 -56  16 -40  24  -8  56  48]
 [ 80 -64 -64  56 -16  40 -24   8 -56 -48]
 [-60  48  48 -42  12 -30  18  -6  42  36]
 [ 90 -72 -72  63 -18  45 -27   9 -63 -54]
 [-40  32  32 -28   8 -20  12  -4  28  24]
 [-50  40  40 -35  10 -25  15  -5  35  30]
 [-10   8   8  -7   2  -5   3  -1   7   6]
 [ 50 -40 -40  35 -10  25 -15   5 -35 -30]]
[ -4   9  16 -15   8 -14   7   4   8   1]
[-60   8  64  56  12  45  12  -5   7 -30]
109


In [91]:
#98

phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

In [99]:
#99

X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
print(M)
M &= (X.sum(axis=-1) == n)
print(M)
print(X[M])

[ True  True False]
[False  True False]
[[2. 0. 1. 1.]]


In [111]:
#100

X = np.random.randn(100)
N = 1000
sample_indices = np.random.randint(0, X.shape[0], (N, 10))
samples = X[sample_indices]
samples = np.mean(samples, axis=-1)
print(np.quantile(samples, 0.975))
conf_interval = np.percentile(samples, [2.5, 97.5])
print(conf_interval)

0.523888923312389
[-0.63    0.5239]
